name: Build & Validate

on: push

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build
        run: npm run build
