name: Build & Validate

on: push

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm install
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build
        run: npm run build
