name: Master

on:
  push:
    branches:
      - master

jobs:
  wget:
    name: test wget
    runs-on: ubuntu-latest
    steps:
      - name: get
        run: wget -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip
      - name: unzip
        run: unzip /tmp/protoc.zip
      - name: ls
        run: ls -al /tmp

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
